### ISSUE TITLE
Requiring unknown module 

### ISSUE THREAD

**Issue by Bjayteh** [PramodVemulapalli/reactnative-expo-firebase-auth#3]
I upgraded the expo sdk to 26.0.0.
i also upgraded react-native to the appropriate version.
I ran yarn install.
Started my XDE and connect my phone.
But when i open the project i get an error like this:
![37153475-d91195a2-2302-11e8-8503-5a2c164afc01](https://user-images.githubusercontent.com/24341372/43878529-33a7c4be-9b8f-11e8-9466-f3b9939e6ecf.png)

**Comment by PramodVemulapalli** [comment]
@Bjayteh 
Thanks for logging the issue. I have upgraded all packages to latest and upgraded expo to 28.0.0. I also fixed some minor issues with react-navigator.  Hope this helps. Let me know if this fixes the issue. 

~ Pramod

**Comment by PramodVemulapalli** [comment]
Marking issue as closed.

**Comment by PramodVemulapalli** [comment]
Marking issue as closed.
